/**
 * Floor plan data. Coordinates are in feet; (0,0) is top-left.
 * Each room: { id, name, x, y, w, h, ceiling?, exterior?, color? }
 *
 * Approximate layout reconstructed from the source plan. The editor
 * lets you reposition, resize, rename, and add rooms.
 */
window.DEFAULT_PLAN = {
  units: "ft",
  bounds: { w: 102, h: 84 },
  rooms: [
    /* ---- Primary Suite (NW) ---- */
    {
      id: "patio-nw-spa",
      name: "Covered Patio",
      sub: "OPT. SPA",
      x: 4,
      y: 0,
      w: 14,
      h: 10,
      exterior: true,
    },
    {
      id: "ensuite-shower",
      name: "Shower / Soaker Tub",
      x: 4,
      y: 10,
      w: 8,
      h: 7,
    },
    { id: "ensuite", name: "Ensuite", x: 4, y: 17, w: 14, h: 9 },
    { id: "wic-pri-l", name: "W.I.C.", x: 4, y: 26, w: 7, h: 6 },
    { id: "wic-pri-r", name: "W.I.C.", x: 11, y: 26, w: 7, h: 6 },
    {
      id: "primary-br",
      name: "Primary Bedroom",
      x: 18,
      y: 17,
      w: 16,
      h: 12,
      ceiling: 10,
    },
    {
      id: "patio-nw",
      name: "Covered Patio",
      x: 18,
      y: 6,
      w: 16,
      h: 7,
      exterior: true,
    },
    { id: "pantry", name: "Pantry", x: 34, y: 22, w: 8, h: 8 },

    /* ---- Service / Garage / Entry ---- */
    {
      id: "garage",
      name: "4-Car Garage",
      x: 0,
      y: 32,
      w: 29,
      h: 30,
    },
    {
      id: "mech",
      name: "Mech Room",
      x: 29,
      y: 30,
      w: 5,
      h: 8,
    },
    {
      id: "laundry",
      name: "Laundry & Mudroom",
      x: 34,
      y: 30,
      w: 11,
      h: 13,
      ceiling: 10,
    },
    {
      id: "foyer",
      name: "Foyer",
      x: 34,
      y: 43,
      w: 11,
      h: 7,
      ceiling: 10,
    },
    { id: "storage", name: "Storage Room", x: 29, y: 38, w: 5, h: 10 },
    { id: "storage-nook", name: "Storage Nook", x: 12, y: 62, w: 6, h: 13 },
    {
      id: "covered-entry",
      name: "Covered Entry",
      x: 22,
      y: 62,
      w: 11,
      h: 18,
      exterior: true,
    },

    /* ---- Center great-room ---- */
    {
      id: "kitchen",
      name: "Kitchen",
      x: 45,
      y: 27,
      w: 12,
      h: 23,
    },
    {
      id: "dining",
      name: "Dining Room",
      x: 57,
      y: 27,
      w: 10,
      h: 23,
    },
    {
      id: "living",
      name: "Living Room",
      x: 67,
      y: 27,
      w: 15,
      h: 23,
      ceiling: 14,
    },
    {
      id: "patio-top",
      name: "Covered Patio",
      sub: "16' SOFFIT",
      x: 42,
      y: 0,
      w: 26,
      h: 22,
      exterior: true,
    },
    {
      id: "patio-south",
      name: "Covered Patio",
      x: 33,
      y: 50,
      w: 37,
      h: 10,
      exterior: true,
    },

    /* ---- Bedrooms 1 & 2 (NE) ---- */
    {
      id: "br2",
      name: "Bedroom 2",
      x: 68,
      y: 7,
      w: 11,
      h: 12,
      ceiling: 10,
    },
    { id: "bath-be", name: "Bath", x: 79, y: 7, w: 5, h: 14 },
    {
      id: "br1",
      name: "Bedroom 1",
      x: 84,
      y: 7,
      w: 11,
      h: 12,
      ceiling: 10,
    },
    { id: "wic-br2", name: "W.I.C.", x: 70, y: 19, w: 7, h: 5 },
    { id: "wic-br1", name: "W.I.C.", x: 86, y: 19, w: 7, h: 5 },
    {
      id: "patio-east",
      name: "Covered Patio",
      sub: "14' SOFFIT",
      x: 95,
      y: 7,
      w: 7,
      h: 24,
      exterior: true,
    },

    /* ---- Flex / Guest wing (SE) ---- */
    { id: "wardrobe", name: "Wardrobe", x: 82, y: 24, w: 6, h: 6 },
    { id: "bath-se", name: "Bath", x: 88, y: 24, w: 9, h: 6 },
    {
      id: "flex",
      name: "Flex / Guest Suite",
      x: 82,
      y: 31,
      w: 18,
      h: 14,
      ceiling: 10,
    },
    { id: "pwdr", name: "PWDR", x: 78, y: 45, w: 5, h: 5 },
    { id: "kitchenette", name: "Kitchenette", x: 83, y: 45, w: 10, h: 5 },
    {
      id: "office",
      name: "Office",
      x: 82,
      y: 50,
      w: 14,
      h: 10,
      ceiling: 10,
    },
  ],
};
